// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package main

import "fmt"
import "encoding/json"
import "reflect"

// This class does not get 'AdditionalProperties = false' in the schema generation,
// so it can be extended with arbitrary JSON properties to allow adding custom
// data.
type CustomDataType struct {
	// VendorId corresponds to the JSON schema field "vendorId".
	VendorId string `json:"vendorId" yaml:"vendorId"`
}

type PublishFirmwareStatusEnumType string

const PublishFirmwareStatusEnumTypeChecksumVerified PublishFirmwareStatusEnumType = "ChecksumVerified"
const PublishFirmwareStatusEnumTypeDownloadFailed PublishFirmwareStatusEnumType = "DownloadFailed"
const PublishFirmwareStatusEnumTypeDownloadPaused PublishFirmwareStatusEnumType = "DownloadPaused"
const PublishFirmwareStatusEnumTypeDownloadScheduled PublishFirmwareStatusEnumType = "DownloadScheduled"
const PublishFirmwareStatusEnumTypeDownloaded PublishFirmwareStatusEnumType = "Downloaded"
const PublishFirmwareStatusEnumTypeDownloading PublishFirmwareStatusEnumType = "Downloading"

// UnmarshalJSON implements json.Unmarshaler.
func (j *PublishFirmwareStatusEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_PublishFirmwareStatusEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_PublishFirmwareStatusEnumType, v)
	}
	*j = PublishFirmwareStatusEnumType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PublishFirmwareStatusEnumType_1) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_PublishFirmwareStatusEnumType_1 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_PublishFirmwareStatusEnumType_1, v)
	}
	*j = PublishFirmwareStatusEnumType_1(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomDataType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["vendorId"]; !ok || v == nil {
		return fmt.Errorf("field vendorId in CustomDataType: required")
	}
	type Plain CustomDataType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CustomDataType(plain)
	return nil
}

const PublishFirmwareStatusEnumTypeIdle PublishFirmwareStatusEnumType = "Idle"
const PublishFirmwareStatusEnumTypeInvalidChecksum PublishFirmwareStatusEnumType = "InvalidChecksum"
const PublishFirmwareStatusEnumTypePublishFailed PublishFirmwareStatusEnumType = "PublishFailed"
const PublishFirmwareStatusEnumTypePublished PublishFirmwareStatusEnumType = "Published"

type PublishFirmwareStatusEnumType_1 string

const PublishFirmwareStatusEnumType_1_ChecksumVerified PublishFirmwareStatusEnumType_1 = "ChecksumVerified"
const PublishFirmwareStatusEnumType_1_DownloadFailed PublishFirmwareStatusEnumType_1 = "DownloadFailed"
const PublishFirmwareStatusEnumType_1_DownloadPaused PublishFirmwareStatusEnumType_1 = "DownloadPaused"
const PublishFirmwareStatusEnumType_1_DownloadScheduled PublishFirmwareStatusEnumType_1 = "DownloadScheduled"
const PublishFirmwareStatusEnumType_1_Downloaded PublishFirmwareStatusEnumType_1 = "Downloaded"
const PublishFirmwareStatusEnumType_1_Downloading PublishFirmwareStatusEnumType_1 = "Downloading"
const PublishFirmwareStatusEnumType_1_Idle PublishFirmwareStatusEnumType_1 = "Idle"
const PublishFirmwareStatusEnumType_1_InvalidChecksum PublishFirmwareStatusEnumType_1 = "InvalidChecksum"
const PublishFirmwareStatusEnumType_1_PublishFailed PublishFirmwareStatusEnumType_1 = "PublishFailed"
const PublishFirmwareStatusEnumType_1_Published PublishFirmwareStatusEnumType_1 = "Published"

type PublishFirmwareStatusNotificationRequestJson struct {
	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`

	// Required if status is Published. Can be multiple URI’s, if the Local
	// Controller supports e.g. HTTP, HTTPS, and FTP.
	//
	Location []string `json:"location,omitempty" yaml:"location,omitempty"`

	// The request id that was
	// provided in the
	// PublishFirmwareRequest which
	// triggered this action.
	//
	RequestId *int `json:"requestId,omitempty" yaml:"requestId,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status PublishFirmwareStatusEnumType_1 `json:"status" yaml:"status"`
}

var enumValues_PublishFirmwareStatusEnumType = []interface{}{
	"Idle",
	"DownloadScheduled",
	"Downloading",
	"Downloaded",
	"Published",
	"DownloadFailed",
	"DownloadPaused",
	"InvalidChecksum",
	"ChecksumVerified",
	"PublishFailed",
}
var enumValues_PublishFirmwareStatusEnumType_1 = []interface{}{
	"Idle",
	"DownloadScheduled",
	"Downloading",
	"Downloaded",
	"Published",
	"DownloadFailed",
	"DownloadPaused",
	"InvalidChecksum",
	"ChecksumVerified",
	"PublishFailed",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PublishFirmwareStatusNotificationRequestJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["status"]; !ok || v == nil {
		return fmt.Errorf("field status in PublishFirmwareStatusNotificationRequestJson: required")
	}
	type Plain PublishFirmwareStatusNotificationRequestJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if len(plain.Location) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "location", 1)
	}
	*j = PublishFirmwareStatusNotificationRequestJson(plain)
	return nil
}
