// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package SignCertificateRequest

import "fmt"
import "reflect"
import "encoding/json"

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomDataType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["vendorId"]; !ok || v == nil {
		return fmt.Errorf("field vendorId in CustomDataType: required")
	}
	type Plain CustomDataType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CustomDataType(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CertificateSigningUseEnumType_1) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CertificateSigningUseEnumType_1 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CertificateSigningUseEnumType_1, v)
	}
	*j = CertificateSigningUseEnumType_1(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CertificateSigningUseEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CertificateSigningUseEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CertificateSigningUseEnumType, v)
	}
	*j = CertificateSigningUseEnumType(v)
	return nil
}

type CertificateSigningUseEnumType string

const CertificateSigningUseEnumTypeChargingStationCertificate CertificateSigningUseEnumType = "ChargingStationCertificate"
const CertificateSigningUseEnumTypeV2GCertificate CertificateSigningUseEnumType = "V2GCertificate"

type CertificateSigningUseEnumType_1 string

const CertificateSigningUseEnumType_1_ChargingStationCertificate CertificateSigningUseEnumType_1 = "ChargingStationCertificate"
const CertificateSigningUseEnumType_1_V2GCertificate CertificateSigningUseEnumType_1 = "V2GCertificate"

// This class does not get 'AdditionalProperties = false' in the schema generation,
// so it can be extended with arbitrary JSON properties to allow adding custom
// data.
type CustomDataType struct {
	// VendorId corresponds to the JSON schema field "vendorId".
	VendorId string `json:"vendorId" yaml:"vendorId"`
}

type SignCertificateRequestJson struct {
	// CertificateType corresponds to the JSON schema field "certificateType".
	CertificateType *CertificateSigningUseEnumType_1 `json:"certificateType,omitempty" yaml:"certificateType,omitempty"`

	// The Charging Station SHALL send the public key in form of a Certificate Signing
	// Request (CSR) as described in RFC 2986 [22] and then PEM encoded, using the
	// &lt;&lt;signcertificaterequest,SignCertificateRequest&gt;&gt; message.
	//
	Csr string `json:"csr" yaml:"csr"`

	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`
}

var enumValues_CertificateSigningUseEnumType = []interface{}{
	"ChargingStationCertificate",
	"V2GCertificate",
}
var enumValues_CertificateSigningUseEnumType_1 = []interface{}{
	"ChargingStationCertificate",
	"V2GCertificate",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SignCertificateRequestJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["csr"]; !ok || v == nil {
		return fmt.Errorf("field csr in SignCertificateRequestJson: required")
	}
	type Plain SignCertificateRequestJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = SignCertificateRequestJson(plain)
	return nil
}
