// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package SetNetworkProfileRequest

import "fmt"
import "reflect"
import "encoding/json"

// UnmarshalJSON implements json.Unmarshaler.
func (j *VPNType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["key"]; !ok || v == nil {
		return fmt.Errorf("field key in VPNType: required")
	}
	if v, ok := raw["password"]; !ok || v == nil {
		return fmt.Errorf("field password in VPNType: required")
	}
	if v, ok := raw["server"]; !ok || v == nil {
		return fmt.Errorf("field server in VPNType: required")
	}
	if v, ok := raw["type"]; !ok || v == nil {
		return fmt.Errorf("field type in VPNType: required")
	}
	if v, ok := raw["user"]; !ok || v == nil {
		return fmt.Errorf("field user in VPNType: required")
	}
	type Plain VPNType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = VPNType(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *VPNEnumType_1) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_VPNEnumType_1 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_VPNEnumType_1, v)
	}
	*j = VPNEnumType_1(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *APNAuthenticationEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_APNAuthenticationEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_APNAuthenticationEnumType, v)
	}
	*j = APNAuthenticationEnumType(v)
	return nil
}

const APNAuthenticationEnumTypeCHAP APNAuthenticationEnumType = "CHAP"
const APNAuthenticationEnumTypeNONE APNAuthenticationEnumType = "NONE"
const APNAuthenticationEnumTypePAP APNAuthenticationEnumType = "PAP"
const APNAuthenticationEnumTypeAUTO APNAuthenticationEnumType = "AUTO"

type APNAuthenticationEnumType_1 string

// UnmarshalJSON implements json.Unmarshaler.
func (j *OCPPVersionEnumType_1) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OCPPVersionEnumType_1 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_OCPPVersionEnumType_1, v)
	}
	*j = OCPPVersionEnumType_1(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *APNAuthenticationEnumType_1) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_APNAuthenticationEnumType_1 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_APNAuthenticationEnumType_1, v)
	}
	*j = APNAuthenticationEnumType_1(v)
	return nil
}

type APNAuthenticationEnumType string

const APNAuthenticationEnumType_1_NONE APNAuthenticationEnumType_1 = "NONE"
const APNAuthenticationEnumType_1_PAP APNAuthenticationEnumType_1 = "PAP"
const APNAuthenticationEnumType_1_AUTO APNAuthenticationEnumType_1 = "AUTO"

// This class does not get 'AdditionalProperties = false' in the schema generation,
// so it can be extended with arbitrary JSON properties to allow adding custom
// data.
type CustomDataType struct {
	// VendorId corresponds to the JSON schema field "vendorId".
	VendorId string `json:"vendorId" yaml:"vendorId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomDataType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["vendorId"]; !ok || v == nil {
		return fmt.Errorf("field vendorId in CustomDataType: required")
	}
	type Plain CustomDataType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CustomDataType(plain)
	return nil
}

// APN
// urn:x-oca:ocpp:uid:2:233134
// Collection of configuration data needed to make a data-connection over a
// cellular network.
//
// NOTE: When asking a GSM modem to dial in, it is possible to specify which mobile
// operator should be used. This can be done with the mobile country code (MCC) in
// combination with a mobile network code (MNC). Example: If your preferred network
// is Vodafone Netherlands, the MCC=204 and the MNC=04 which means the key
// PreferredNetwork = 20404 Some modems allows to specify a preferred network,
// which means, if this network is not available, a different network is used. If
// you specify UseOnlyPreferredNetwork and this network is not available, the modem
// will not dial in.
//
type APNType struct {
	// APN. APN. URI
	// urn:x-oca:ocpp:uid:1:568814
	// The Access Point Name as an URL.
	//
	Apn string `json:"apn" yaml:"apn"`

	// ApnAuthentication corresponds to the JSON schema field "apnAuthentication".
	ApnAuthentication APNAuthenticationEnumType_1 `json:"apnAuthentication" yaml:"apnAuthentication"`

	// APN. APN. Password
	// urn:x-oca:ocpp:uid:1:568819
	// APN Password.
	//
	ApnPassword *string `json:"apnPassword,omitempty" yaml:"apnPassword,omitempty"`

	// APN. APN. User_ Name
	// urn:x-oca:ocpp:uid:1:568818
	// APN username.
	//
	ApnUserName *string `json:"apnUserName,omitempty" yaml:"apnUserName,omitempty"`

	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`

	// APN. Preferred_ Network. Mobile_ Network_ ID
	// urn:x-oca:ocpp:uid:1:568822
	// Preferred network, written as MCC and MNC concatenated. See note.
	//
	PreferredNetwork *string `json:"preferredNetwork,omitempty" yaml:"preferredNetwork,omitempty"`

	// APN. SIMPIN. PIN_ Code
	// urn:x-oca:ocpp:uid:1:568821
	// SIM card pin code.
	//
	SimPin *int `json:"simPin,omitempty" yaml:"simPin,omitempty"`

	// APN. Use_ Only_ Preferred_ Network. Indicator
	// urn:x-oca:ocpp:uid:1:568824
	// Default: false. Use only the preferred Network, do
	// not dial in when not available. See Note.
	//
	UseOnlyPreferredNetwork bool `json:"useOnlyPreferredNetwork,omitempty" yaml:"useOnlyPreferredNetwork,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *APNType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["apn"]; !ok || v == nil {
		return fmt.Errorf("field apn in APNType: required")
	}
	if v, ok := raw["apnAuthentication"]; !ok || v == nil {
		return fmt.Errorf("field apnAuthentication in APNType: required")
	}
	type Plain APNType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if v, ok := raw["useOnlyPreferredNetwork"]; !ok || v == nil {
		plain.UseOnlyPreferredNetwork = false
	}
	*j = APNType(plain)
	return nil
}

type OCPPInterfaceEnumType string

// UnmarshalJSON implements json.Unmarshaler.
func (j *OCPPTransportEnumType_1) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OCPPTransportEnumType_1 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_OCPPTransportEnumType_1, v)
	}
	*j = OCPPTransportEnumType_1(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OCPPInterfaceEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OCPPInterfaceEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_OCPPInterfaceEnumType, v)
	}
	*j = OCPPInterfaceEnumType(v)
	return nil
}

const OCPPInterfaceEnumTypeWired0 OCPPInterfaceEnumType = "Wired0"
const OCPPInterfaceEnumTypeWired1 OCPPInterfaceEnumType = "Wired1"
const OCPPInterfaceEnumTypeWired2 OCPPInterfaceEnumType = "Wired2"
const OCPPInterfaceEnumTypeWired3 OCPPInterfaceEnumType = "Wired3"
const OCPPInterfaceEnumTypeWireless0 OCPPInterfaceEnumType = "Wireless0"
const OCPPInterfaceEnumTypeWireless1 OCPPInterfaceEnumType = "Wireless1"
const OCPPInterfaceEnumTypeWireless2 OCPPInterfaceEnumType = "Wireless2"
const OCPPInterfaceEnumTypeWireless3 OCPPInterfaceEnumType = "Wireless3"

type OCPPTransportEnumType string

const OCPPInterfaceEnumType_1_Wireless3 OCPPInterfaceEnumType_1 = "Wireless3"

// UnmarshalJSON implements json.Unmarshaler.
func (j *OCPPTransportEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OCPPTransportEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_OCPPTransportEnumType, v)
	}
	*j = OCPPTransportEnumType(v)
	return nil
}

type OCPPInterfaceEnumType_1 string

const OCPPInterfaceEnumType_1_Wireless2 OCPPInterfaceEnumType_1 = "Wireless2"
const OCPPInterfaceEnumType_1_Wireless1 OCPPInterfaceEnumType_1 = "Wireless1"
const OCPPInterfaceEnumType_1_Wireless0 OCPPInterfaceEnumType_1 = "Wireless0"

// UnmarshalJSON implements json.Unmarshaler.
func (j *OCPPVersionEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OCPPVersionEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_OCPPVersionEnumType, v)
	}
	*j = OCPPVersionEnumType(v)
	return nil
}

const OCPPInterfaceEnumType_1_Wired3 OCPPInterfaceEnumType_1 = "Wired3"
const OCPPInterfaceEnumType_1_Wired2 OCPPInterfaceEnumType_1 = "Wired2"
const OCPPInterfaceEnumType_1_Wired1 OCPPInterfaceEnumType_1 = "Wired1"

// Communication_ Function
// urn:x-oca:ocpp:uid:2:233304
// The NetworkConnectionProfile defines the functional and technical parameters of
// a communication link.
//
type NetworkConnectionProfileType struct {
	// Apn corresponds to the JSON schema field "apn".
	Apn *APNType `json:"apn,omitempty" yaml:"apn,omitempty"`

	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`

	// Duration in seconds before a message send by the Charging Station via this
	// network connection times-out.
	// The best setting depends on the underlying network and response times of the
	// CSMS.
	// If you are looking for a some guideline: use 30 seconds as a starting point.
	//
	MessageTimeout int `json:"messageTimeout" yaml:"messageTimeout"`

	// Communication_ Function. OCPP_ Central_ System_ URL. URI
	// urn:x-oca:ocpp:uid:1:569357
	// URL of the CSMS(s) that this Charging Station  communicates with.
	//
	OcppCsmsUrl string `json:"ocppCsmsUrl" yaml:"ocppCsmsUrl"`

	// OcppInterface corresponds to the JSON schema field "ocppInterface".
	OcppInterface OCPPInterfaceEnumType `json:"ocppInterface" yaml:"ocppInterface"`

	// OcppTransport corresponds to the JSON schema field "ocppTransport".
	OcppTransport OCPPTransportEnumType `json:"ocppTransport" yaml:"ocppTransport"`

	// OcppVersion corresponds to the JSON schema field "ocppVersion".
	OcppVersion OCPPVersionEnumType `json:"ocppVersion" yaml:"ocppVersion"`

	// This field specifies the security profile used when connecting to the CSMS with
	// this NetworkConnectionProfile.
	//
	SecurityProfile int `json:"securityProfile" yaml:"securityProfile"`

	// Vpn corresponds to the JSON schema field "vpn".
	Vpn *VPNType `json:"vpn,omitempty" yaml:"vpn,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OCPPInterfaceEnumType_1) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OCPPInterfaceEnumType_1 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_OCPPInterfaceEnumType_1, v)
	}
	*j = OCPPInterfaceEnumType_1(v)
	return nil
}

const APNAuthenticationEnumType_1_CHAP APNAuthenticationEnumType_1 = "CHAP"

// UnmarshalJSON implements json.Unmarshaler.
func (j *VPNEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_VPNEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_VPNEnumType, v)
	}
	*j = VPNEnumType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NetworkConnectionProfileType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["messageTimeout"]; !ok || v == nil {
		return fmt.Errorf("field messageTimeout in NetworkConnectionProfileType: required")
	}
	if v, ok := raw["ocppCsmsUrl"]; !ok || v == nil {
		return fmt.Errorf("field ocppCsmsUrl in NetworkConnectionProfileType: required")
	}
	if v, ok := raw["ocppInterface"]; !ok || v == nil {
		return fmt.Errorf("field ocppInterface in NetworkConnectionProfileType: required")
	}
	if v, ok := raw["ocppTransport"]; !ok || v == nil {
		return fmt.Errorf("field ocppTransport in NetworkConnectionProfileType: required")
	}
	if v, ok := raw["ocppVersion"]; !ok || v == nil {
		return fmt.Errorf("field ocppVersion in NetworkConnectionProfileType: required")
	}
	if v, ok := raw["securityProfile"]; !ok || v == nil {
		return fmt.Errorf("field securityProfile in NetworkConnectionProfileType: required")
	}
	type Plain NetworkConnectionProfileType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = NetworkConnectionProfileType(plain)
	return nil
}

const OCPPInterfaceEnumType_1_Wired0 OCPPInterfaceEnumType_1 = "Wired0"
const OCPPTransportEnumTypeJSON OCPPTransportEnumType = "JSON"
const OCPPTransportEnumTypeSOAP OCPPTransportEnumType = "SOAP"

type OCPPTransportEnumType_1 string

const OCPPTransportEnumType_1_JSON OCPPTransportEnumType_1 = "JSON"
const OCPPTransportEnumType_1_SOAP OCPPTransportEnumType_1 = "SOAP"

type OCPPVersionEnumType string

const OCPPVersionEnumTypeOCPP12 OCPPVersionEnumType = "OCPP12"
const OCPPVersionEnumTypeOCPP15 OCPPVersionEnumType = "OCPP15"
const OCPPVersionEnumTypeOCPP16 OCPPVersionEnumType = "OCPP16"
const OCPPVersionEnumTypeOCPP20 OCPPVersionEnumType = "OCPP20"

type OCPPVersionEnumType_1 string

const OCPPVersionEnumType_1_OCPP12 OCPPVersionEnumType_1 = "OCPP12"
const OCPPVersionEnumType_1_OCPP15 OCPPVersionEnumType_1 = "OCPP15"
const OCPPVersionEnumType_1_OCPP16 OCPPVersionEnumType_1 = "OCPP16"
const OCPPVersionEnumType_1_OCPP20 OCPPVersionEnumType_1 = "OCPP20"

type SetNetworkProfileRequestJson struct {
	// Slot in which the configuration should be stored.
	//
	ConfigurationSlot int `json:"configurationSlot" yaml:"configurationSlot"`

	// ConnectionData corresponds to the JSON schema field "connectionData".
	ConnectionData NetworkConnectionProfileType `json:"connectionData" yaml:"connectionData"`

	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`
}

type VPNEnumType string

const VPNEnumTypeIKEv2 VPNEnumType = "IKEv2"
const VPNEnumTypeIPSec VPNEnumType = "IPSec"
const VPNEnumTypeL2TP VPNEnumType = "L2TP"
const VPNEnumTypePPTP VPNEnumType = "PPTP"

type VPNEnumType_1 string

const VPNEnumType_1_IKEv2 VPNEnumType_1 = "IKEv2"
const VPNEnumType_1_IPSec VPNEnumType_1 = "IPSec"
const VPNEnumType_1_L2TP VPNEnumType_1 = "L2TP"
const VPNEnumType_1_PPTP VPNEnumType_1 = "PPTP"

// VPN
// urn:x-oca:ocpp:uid:2:233268
// VPN Configuration settings
//
type VPNType struct {
	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`

	// VPN. Group. Group_ Name
	// urn:x-oca:ocpp:uid:1:569274
	// VPN group.
	//
	Group *string `json:"group,omitempty" yaml:"group,omitempty"`

	// VPN. Key. VPN_ Key
	// urn:x-oca:ocpp:uid:1:569276
	// VPN shared secret.
	//
	Key string `json:"key" yaml:"key"`

	// VPN. Password. Password
	// urn:x-oca:ocpp:uid:1:569275
	// VPN Password.
	//
	Password string `json:"password" yaml:"password"`

	// VPN. Server. URI
	// urn:x-oca:ocpp:uid:1:569272
	// VPN Server Address
	//
	Server string `json:"server" yaml:"server"`

	// Type corresponds to the JSON schema field "type".
	Type VPNEnumType `json:"type" yaml:"type"`

	// VPN. User. User_ Name
	// urn:x-oca:ocpp:uid:1:569273
	// VPN User
	//
	User string `json:"user" yaml:"user"`
}

var enumValues_APNAuthenticationEnumType = []interface{}{
	"CHAP",
	"NONE",
	"PAP",
	"AUTO",
}
var enumValues_APNAuthenticationEnumType_1 = []interface{}{
	"CHAP",
	"NONE",
	"PAP",
	"AUTO",
}
var enumValues_OCPPInterfaceEnumType = []interface{}{
	"Wired0",
	"Wired1",
	"Wired2",
	"Wired3",
	"Wireless0",
	"Wireless1",
	"Wireless2",
	"Wireless3",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetNetworkProfileRequestJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["configurationSlot"]; !ok || v == nil {
		return fmt.Errorf("field configurationSlot in SetNetworkProfileRequestJson: required")
	}
	if v, ok := raw["connectionData"]; !ok || v == nil {
		return fmt.Errorf("field connectionData in SetNetworkProfileRequestJson: required")
	}
	type Plain SetNetworkProfileRequestJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = SetNetworkProfileRequestJson(plain)
	return nil
}

var enumValues_OCPPInterfaceEnumType_1 = []interface{}{
	"Wired0",
	"Wired1",
	"Wired2",
	"Wired3",
	"Wireless0",
	"Wireless1",
	"Wireless2",
	"Wireless3",
}
var enumValues_OCPPTransportEnumType = []interface{}{
	"JSON",
	"SOAP",
}
var enumValues_OCPPTransportEnumType_1 = []interface{}{
	"JSON",
	"SOAP",
}
var enumValues_OCPPVersionEnumType = []interface{}{
	"OCPP12",
	"OCPP15",
	"OCPP16",
	"OCPP20",
}
var enumValues_OCPPVersionEnumType_1 = []interface{}{
	"OCPP12",
	"OCPP15",
	"OCPP16",
	"OCPP20",
}
var enumValues_VPNEnumType = []interface{}{
	"IKEv2",
	"IPSec",
	"L2TP",
	"PPTP",
}
var enumValues_VPNEnumType_1 = []interface{}{
	"IKEv2",
	"IPSec",
	"L2TP",
	"PPTP",
}
