// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package ReserveNowRequest

import "fmt"
import "encoding/json"
import "reflect"

// UnmarshalJSON implements json.Unmarshaler.
func (j *IdTokenEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_IdTokenEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_IdTokenEnumType, v)
	}
	*j = IdTokenEnumType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomDataType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["vendorId"]; !ok || v == nil {
		return fmt.Errorf("field vendorId in CustomDataType: required")
	}
	type Plain CustomDataType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CustomDataType(plain)
	return nil
}

// Contains a case insensitive identifier to use for the authorization and the type
// of authorization to support multiple forms of identifiers.
//
type AdditionalInfoType struct {
	// This field specifies the additional IdToken.
	//
	AdditionalIdToken string `json:"additionalIdToken" yaml:"additionalIdToken"`

	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`

	// This defines the type of the additionalIdToken. This is a custom type, so the
	// implementation needs to be agreed upon by all involved parties.
	//
	Type string `json:"type" yaml:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AdditionalInfoType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["additionalIdToken"]; !ok || v == nil {
		return fmt.Errorf("field additionalIdToken in AdditionalInfoType: required")
	}
	if v, ok := raw["type"]; !ok || v == nil {
		return fmt.Errorf("field type in AdditionalInfoType: required")
	}
	type Plain AdditionalInfoType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = AdditionalInfoType(plain)
	return nil
}

type ConnectorEnumType string

// UnmarshalJSON implements json.Unmarshaler.
func (j *IdTokenType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["idToken"]; !ok || v == nil {
		return fmt.Errorf("field idToken in IdTokenType: required")
	}
	if v, ok := raw["type"]; !ok || v == nil {
		return fmt.Errorf("field type in IdTokenType: required")
	}
	type Plain IdTokenType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if len(plain.AdditionalInfo) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "additionalInfo", 1)
	}
	*j = IdTokenType(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ConnectorEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ConnectorEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ConnectorEnumType, v)
	}
	*j = ConnectorEnumType(v)
	return nil
}

const ConnectorEnumTypeCCCS1 ConnectorEnumType = "cCCS1"
const ConnectorEnumTypeCCCS2 ConnectorEnumType = "cCCS2"
const ConnectorEnumTypeCG105 ConnectorEnumType = "cG105"
const ConnectorEnumTypeCTesla ConnectorEnumType = "cTesla"
const ConnectorEnumTypeCType1 ConnectorEnumType = "cType1"
const ConnectorEnumTypeCType2 ConnectorEnumType = "cType2"
const ConnectorEnumTypeS3091P16A ConnectorEnumType = "s309-1P-16A"
const ConnectorEnumTypeS3091P32A ConnectorEnumType = "s309-1P-32A"
const ConnectorEnumTypeS3093P16A ConnectorEnumType = "s309-3P-16A"
const ConnectorEnumTypeS3093P32A ConnectorEnumType = "s309-3P-32A"
const ConnectorEnumTypeSBS1361 ConnectorEnumType = "sBS1361"
const ConnectorEnumTypeSCEE77 ConnectorEnumType = "sCEE-7-7"
const ConnectorEnumTypeSType2 ConnectorEnumType = "sType2"

// UnmarshalJSON implements json.Unmarshaler.
func (j *ConnectorEnumType_1) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ConnectorEnumType_1 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ConnectorEnumType_1, v)
	}
	*j = ConnectorEnumType_1(v)
	return nil
}

const ConnectorEnumTypeOther1PhMax16A ConnectorEnumType = "Other1PhMax16A"
const ConnectorEnumTypeOther1PhOver16A ConnectorEnumType = "Other1PhOver16A"
const ConnectorEnumTypeOther3Ph ConnectorEnumType = "Other3Ph"
const ConnectorEnumTypePan ConnectorEnumType = "Pan"
const ConnectorEnumTypeSType3 ConnectorEnumType = "sType3"
const ConnectorEnumTypeUndetermined ConnectorEnumType = "Undetermined"
const ConnectorEnumTypeUnknown ConnectorEnumType = "Unknown"
const ConnectorEnumTypeWInductive ConnectorEnumType = "wInductive"
const ConnectorEnumTypeWResonant ConnectorEnumType = "wResonant"

type ConnectorEnumType_1 string

const ConnectorEnumType_1_CCCS1 ConnectorEnumType_1 = "cCCS1"
const ConnectorEnumType_1_CCCS2 ConnectorEnumType_1 = "cCCS2"
const ConnectorEnumType_1_CG105 ConnectorEnumType_1 = "cG105"
const ConnectorEnumType_1_CTesla ConnectorEnumType_1 = "cTesla"
const ConnectorEnumType_1_CType1 ConnectorEnumType_1 = "cType1"
const ConnectorEnumType_1_CType2 ConnectorEnumType_1 = "cType2"
const ConnectorEnumType_1_Other1PhMax16A ConnectorEnumType_1 = "Other1PhMax16A"

// UnmarshalJSON implements json.Unmarshaler.
func (j *IdTokenEnumType_1) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_IdTokenEnumType_1 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_IdTokenEnumType_1, v)
	}
	*j = IdTokenEnumType_1(v)
	return nil
}

const ConnectorEnumType_1_Other1PhOver16A ConnectorEnumType_1 = "Other1PhOver16A"
const ConnectorEnumType_1_Other3Ph ConnectorEnumType_1 = "Other3Ph"
const ConnectorEnumType_1_Pan ConnectorEnumType_1 = "Pan"
const ConnectorEnumType_1_S3091P16A ConnectorEnumType_1 = "s309-1P-16A"
const ConnectorEnumType_1_S3091P32A ConnectorEnumType_1 = "s309-1P-32A"
const ConnectorEnumType_1_S3093P16A ConnectorEnumType_1 = "s309-3P-16A"
const ConnectorEnumType_1_S3093P32A ConnectorEnumType_1 = "s309-3P-32A"
const ConnectorEnumType_1_SBS1361 ConnectorEnumType_1 = "sBS1361"
const ConnectorEnumType_1_SCEE77 ConnectorEnumType_1 = "sCEE-7-7"
const ConnectorEnumType_1_SType2 ConnectorEnumType_1 = "sType2"
const ConnectorEnumType_1_SType3 ConnectorEnumType_1 = "sType3"
const ConnectorEnumType_1_Undetermined ConnectorEnumType_1 = "Undetermined"
const ConnectorEnumType_1_Unknown ConnectorEnumType_1 = "Unknown"
const ConnectorEnumType_1_WInductive ConnectorEnumType_1 = "wInductive"
const ConnectorEnumType_1_WResonant ConnectorEnumType_1 = "wResonant"

// This class does not get 'AdditionalProperties = false' in the schema generation,
// so it can be extended with arbitrary JSON properties to allow adding custom
// data.
type CustomDataType struct {
	// VendorId corresponds to the JSON schema field "vendorId".
	VendorId string `json:"vendorId" yaml:"vendorId"`
}

type IdTokenEnumType string

const IdTokenEnumTypeCentral IdTokenEnumType = "Central"
const IdTokenEnumTypeEMAID IdTokenEnumType = "eMAID"
const IdTokenEnumTypeISO14443 IdTokenEnumType = "ISO14443"
const IdTokenEnumTypeISO15693 IdTokenEnumType = "ISO15693"
const IdTokenEnumTypeKeyCode IdTokenEnumType = "KeyCode"
const IdTokenEnumTypeLocal IdTokenEnumType = "Local"
const IdTokenEnumTypeMacAddress IdTokenEnumType = "MacAddress"
const IdTokenEnumTypeNoAuthorization IdTokenEnumType = "NoAuthorization"

type IdTokenEnumType_1 string

const IdTokenEnumType_1_Central IdTokenEnumType_1 = "Central"
const IdTokenEnumType_1_EMAID IdTokenEnumType_1 = "eMAID"
const IdTokenEnumType_1_ISO14443 IdTokenEnumType_1 = "ISO14443"
const IdTokenEnumType_1_ISO15693 IdTokenEnumType_1 = "ISO15693"
const IdTokenEnumType_1_KeyCode IdTokenEnumType_1 = "KeyCode"
const IdTokenEnumType_1_Local IdTokenEnumType_1 = "Local"
const IdTokenEnumType_1_MacAddress IdTokenEnumType_1 = "MacAddress"
const IdTokenEnumType_1_NoAuthorization IdTokenEnumType_1 = "NoAuthorization"

// UnmarshalJSON implements json.Unmarshaler.
func (j *ReserveNowRequestJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["expiryDateTime"]; !ok || v == nil {
		return fmt.Errorf("field expiryDateTime in ReserveNowRequestJson: required")
	}
	if v, ok := raw["id"]; !ok || v == nil {
		return fmt.Errorf("field id in ReserveNowRequestJson: required")
	}
	if v, ok := raw["idToken"]; !ok || v == nil {
		return fmt.Errorf("field idToken in ReserveNowRequestJson: required")
	}
	type Plain ReserveNowRequestJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ReserveNowRequestJson(plain)
	return nil
}

// Contains a case insensitive identifier to use for the authorization and the type
// of authorization to support multiple forms of identifiers.
//
type IdTokenType struct {
	// AdditionalInfo corresponds to the JSON schema field "additionalInfo".
	AdditionalInfo []AdditionalInfoType `json:"additionalInfo,omitempty" yaml:"additionalInfo,omitempty"`

	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`

	// IdToken is case insensitive. Might hold the hidden id of an RFID tag, but can
	// for example also contain a UUID.
	//
	IdToken string `json:"idToken" yaml:"idToken"`

	// Type corresponds to the JSON schema field "type".
	Type IdTokenEnumType_1 `json:"type" yaml:"type"`
}

type ReserveNowRequestJson struct {
	// ConnectorType corresponds to the JSON schema field "connectorType".
	ConnectorType *ConnectorEnumType_1 `json:"connectorType,omitempty" yaml:"connectorType,omitempty"`

	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`

	// This contains ID of the evse to be reserved.
	//
	EvseId *int `json:"evseId,omitempty" yaml:"evseId,omitempty"`

	// Date and time at which the reservation expires.
	//
	ExpiryDateTime string `json:"expiryDateTime" yaml:"expiryDateTime"`

	// GroupIdToken corresponds to the JSON schema field "groupIdToken".
	GroupIdToken *IdTokenType `json:"groupIdToken,omitempty" yaml:"groupIdToken,omitempty"`

	// Id of reservation.
	//
	Id int `json:"id" yaml:"id"`

	// IdToken corresponds to the JSON schema field "idToken".
	IdToken IdTokenType `json:"idToken" yaml:"idToken"`
}

var enumValues_ConnectorEnumType = []interface{}{
	"cCCS1",
	"cCCS2",
	"cG105",
	"cTesla",
	"cType1",
	"cType2",
	"s309-1P-16A",
	"s309-1P-32A",
	"s309-3P-16A",
	"s309-3P-32A",
	"sBS1361",
	"sCEE-7-7",
	"sType2",
	"sType3",
	"Other1PhMax16A",
	"Other1PhOver16A",
	"Other3Ph",
	"Pan",
	"wInductive",
	"wResonant",
	"Undetermined",
	"Unknown",
}
var enumValues_ConnectorEnumType_1 = []interface{}{
	"cCCS1",
	"cCCS2",
	"cG105",
	"cTesla",
	"cType1",
	"cType2",
	"s309-1P-16A",
	"s309-1P-32A",
	"s309-3P-16A",
	"s309-3P-32A",
	"sBS1361",
	"sCEE-7-7",
	"sType2",
	"sType3",
	"Other1PhMax16A",
	"Other1PhOver16A",
	"Other3Ph",
	"Pan",
	"wInductive",
	"wResonant",
	"Undetermined",
	"Unknown",
}
var enumValues_IdTokenEnumType = []interface{}{
	"Central",
	"eMAID",
	"ISO14443",
	"ISO15693",
	"KeyCode",
	"Local",
	"MacAddress",
	"NoAuthorization",
}
var enumValues_IdTokenEnumType_1 = []interface{}{
	"Central",
	"eMAID",
	"ISO14443",
	"ISO15693",
	"KeyCode",
	"Local",
	"MacAddress",
	"NoAuthorization",
}
