// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package FirmwareStatusNotificationRequest

import "fmt"
import "encoding/json"
import "reflect"

const FirmwareStatusEnumTypeDownloadFailed FirmwareStatusEnumType = "DownloadFailed"

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomDataType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["vendorId"]; !ok || v == nil {
		return fmt.Errorf("field vendorId in CustomDataType: required")
	}
	type Plain CustomDataType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CustomDataType(plain)
	return nil
}

type FirmwareStatusEnumType string

// UnmarshalJSON implements json.Unmarshaler.
func (j *FirmwareStatusEnumType_1) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_FirmwareStatusEnumType_1 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_FirmwareStatusEnumType_1, v)
	}
	*j = FirmwareStatusEnumType_1(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FirmwareStatusEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_FirmwareStatusEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_FirmwareStatusEnumType, v)
	}
	*j = FirmwareStatusEnumType(v)
	return nil
}

// This class does not get 'AdditionalProperties = false' in the schema generation,
// so it can be extended with arbitrary JSON properties to allow adding custom
// data.
type CustomDataType struct {
	// VendorId corresponds to the JSON schema field "vendorId".
	VendorId string `json:"vendorId" yaml:"vendorId"`
}

const FirmwareStatusEnumTypeDownloadPaused FirmwareStatusEnumType = "DownloadPaused"
const FirmwareStatusEnumTypeDownloadScheduled FirmwareStatusEnumType = "DownloadScheduled"
const FirmwareStatusEnumTypeDownloaded FirmwareStatusEnumType = "Downloaded"
const FirmwareStatusEnumTypeDownloading FirmwareStatusEnumType = "Downloading"
const FirmwareStatusEnumTypeIdle FirmwareStatusEnumType = "Idle"
const FirmwareStatusEnumTypeInstallRebooting FirmwareStatusEnumType = "InstallRebooting"
const FirmwareStatusEnumTypeInstallScheduled FirmwareStatusEnumType = "InstallScheduled"
const FirmwareStatusEnumTypeInstallVerificationFailed FirmwareStatusEnumType = "InstallVerificationFailed"
const FirmwareStatusEnumTypeInstallationFailed FirmwareStatusEnumType = "InstallationFailed"
const FirmwareStatusEnumTypeInstalled FirmwareStatusEnumType = "Installed"
const FirmwareStatusEnumTypeInstalling FirmwareStatusEnumType = "Installing"
const FirmwareStatusEnumTypeInvalidSignature FirmwareStatusEnumType = "InvalidSignature"
const FirmwareStatusEnumTypeSignatureVerified FirmwareStatusEnumType = "SignatureVerified"

type FirmwareStatusEnumType_1 string

const FirmwareStatusEnumType_1_DownloadFailed FirmwareStatusEnumType_1 = "DownloadFailed"
const FirmwareStatusEnumType_1_DownloadPaused FirmwareStatusEnumType_1 = "DownloadPaused"
const FirmwareStatusEnumType_1_DownloadScheduled FirmwareStatusEnumType_1 = "DownloadScheduled"
const FirmwareStatusEnumType_1_Downloaded FirmwareStatusEnumType_1 = "Downloaded"
const FirmwareStatusEnumType_1_Downloading FirmwareStatusEnumType_1 = "Downloading"
const FirmwareStatusEnumType_1_Idle FirmwareStatusEnumType_1 = "Idle"
const FirmwareStatusEnumType_1_InstallRebooting FirmwareStatusEnumType_1 = "InstallRebooting"
const FirmwareStatusEnumType_1_InstallScheduled FirmwareStatusEnumType_1 = "InstallScheduled"
const FirmwareStatusEnumType_1_InstallVerificationFailed FirmwareStatusEnumType_1 = "InstallVerificationFailed"
const FirmwareStatusEnumType_1_InstallationFailed FirmwareStatusEnumType_1 = "InstallationFailed"
const FirmwareStatusEnumType_1_Installed FirmwareStatusEnumType_1 = "Installed"
const FirmwareStatusEnumType_1_Installing FirmwareStatusEnumType_1 = "Installing"
const FirmwareStatusEnumType_1_InvalidSignature FirmwareStatusEnumType_1 = "InvalidSignature"
const FirmwareStatusEnumType_1_SignatureVerified FirmwareStatusEnumType_1 = "SignatureVerified"

type FirmwareStatusNotificationRequestJson struct {
	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`

	// The request id that was provided in the
	// UpdateFirmwareRequest that started this firmware update.
	// This field is mandatory, unless the message was triggered by a
	// TriggerMessageRequest AND there is no firmware update ongoing.
	//
	RequestId *int `json:"requestId,omitempty" yaml:"requestId,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status FirmwareStatusEnumType_1 `json:"status" yaml:"status"`
}

var enumValues_FirmwareStatusEnumType = []interface{}{
	"Downloaded",
	"DownloadFailed",
	"Downloading",
	"DownloadScheduled",
	"DownloadPaused",
	"Idle",
	"InstallationFailed",
	"Installing",
	"Installed",
	"InstallRebooting",
	"InstallScheduled",
	"InstallVerificationFailed",
	"InvalidSignature",
	"SignatureVerified",
}
var enumValues_FirmwareStatusEnumType_1 = []interface{}{
	"Downloaded",
	"DownloadFailed",
	"Downloading",
	"DownloadScheduled",
	"DownloadPaused",
	"Idle",
	"InstallationFailed",
	"Installing",
	"Installed",
	"InstallRebooting",
	"InstallScheduled",
	"InstallVerificationFailed",
	"InvalidSignature",
	"SignatureVerified",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FirmwareStatusNotificationRequestJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["status"]; !ok || v == nil {
		return fmt.Errorf("field status in FirmwareStatusNotificationRequestJson: required")
	}
	type Plain FirmwareStatusNotificationRequestJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = FirmwareStatusNotificationRequestJson(plain)
	return nil
}
