// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package UnlockConnectorResponse

import "fmt"
import "encoding/json"
import "reflect"

const UnlockStatusEnumTypeOngoingAuthorizedTransaction UnlockStatusEnumType = "OngoingAuthorizedTransaction"

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomDataType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["vendorId"]; !ok || v == nil {
		return fmt.Errorf("field vendorId in CustomDataType: required")
	}
	type Plain CustomDataType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CustomDataType(plain)
	return nil
}

// This class does not get 'AdditionalProperties = false' in the schema generation,
// so it can be extended with arbitrary JSON properties to allow adding custom
// data.
type CustomDataType struct {
	// VendorId corresponds to the JSON schema field "vendorId".
	VendorId string `json:"vendorId" yaml:"vendorId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StatusInfoType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["reasonCode"]; !ok || v == nil {
		return fmt.Errorf("field reasonCode in StatusInfoType: required")
	}
	type Plain StatusInfoType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = StatusInfoType(plain)
	return nil
}

type UnlockConnectorResponseJson struct {
	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status UnlockStatusEnumType_1 `json:"status" yaml:"status"`

	// StatusInfo corresponds to the JSON schema field "statusInfo".
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" yaml:"statusInfo,omitempty"`
}

type UnlockStatusEnumType string

// UnmarshalJSON implements json.Unmarshaler.
func (j *UnlockStatusEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_UnlockStatusEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_UnlockStatusEnumType, v)
	}
	*j = UnlockStatusEnumType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UnlockStatusEnumType_1) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_UnlockStatusEnumType_1 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_UnlockStatusEnumType_1, v)
	}
	*j = UnlockStatusEnumType_1(v)
	return nil
}

// Element providing more information about the status.
//
type StatusInfoType struct {
	// Additional text to provide detailed information.
	//
	AdditionalInfo *string `json:"additionalInfo,omitempty" yaml:"additionalInfo,omitempty"`

	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`

	// A predefined code for the reason why the status is returned in this response.
	// The string is case-insensitive.
	//
	ReasonCode string `json:"reasonCode" yaml:"reasonCode"`
}

const UnlockStatusEnumTypeUnknownConnector UnlockStatusEnumType = "UnknownConnector"
const UnlockStatusEnumTypeUnlockFailed UnlockStatusEnumType = "UnlockFailed"
const UnlockStatusEnumTypeUnlocked UnlockStatusEnumType = "Unlocked"

type UnlockStatusEnumType_1 string

const UnlockStatusEnumType_1_OngoingAuthorizedTransaction UnlockStatusEnumType_1 = "OngoingAuthorizedTransaction"
const UnlockStatusEnumType_1_UnknownConnector UnlockStatusEnumType_1 = "UnknownConnector"
const UnlockStatusEnumType_1_UnlockFailed UnlockStatusEnumType_1 = "UnlockFailed"
const UnlockStatusEnumType_1_Unlocked UnlockStatusEnumType_1 = "Unlocked"

var enumValues_UnlockStatusEnumType = []interface{}{
	"Unlocked",
	"UnlockFailed",
	"OngoingAuthorizedTransaction",
	"UnknownConnector",
}
var enumValues_UnlockStatusEnumType_1 = []interface{}{
	"Unlocked",
	"UnlockFailed",
	"OngoingAuthorizedTransaction",
	"UnknownConnector",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UnlockConnectorResponseJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["status"]; !ok || v == nil {
		return fmt.Errorf("field status in UnlockConnectorResponseJson: required")
	}
	type Plain UnlockConnectorResponseJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = UnlockConnectorResponseJson(plain)
	return nil
}
