// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package main

import "fmt"
import "encoding/json"
import "reflect"

type ClearMonitoringResultType struct {
	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`

	// Id of the monitor of which a clear was requested.
	//
	//
	Id int `json:"id" yaml:"id"`

	// Status corresponds to the JSON schema field "status".
	Status ClearMonitoringStatusEnumType `json:"status" yaml:"status"`

	// StatusInfo corresponds to the JSON schema field "statusInfo".
	StatusInfo *StatusInfoType `json:"statusInfo,omitempty" yaml:"statusInfo,omitempty"`
}

type ClearMonitoringStatusEnumType string

const ClearMonitoringStatusEnumTypeAccepted ClearMonitoringStatusEnumType = "Accepted"
const ClearMonitoringStatusEnumTypeNotFound ClearMonitoringStatusEnumType = "NotFound"
const ClearMonitoringStatusEnumTypeRejected ClearMonitoringStatusEnumType = "Rejected"

type ClearMonitoringStatusEnumType_1 string

const ClearMonitoringStatusEnumType_1_Accepted ClearMonitoringStatusEnumType_1 = "Accepted"
const ClearMonitoringStatusEnumType_1_NotFound ClearMonitoringStatusEnumType_1 = "NotFound"
const ClearMonitoringStatusEnumType_1_Rejected ClearMonitoringStatusEnumType_1 = "Rejected"

type ClearVariableMonitoringResponseJson struct {
	// ClearMonitoringResult corresponds to the JSON schema field
	// "clearMonitoringResult".
	ClearMonitoringResult []ClearMonitoringResultType `json:"clearMonitoringResult" yaml:"clearMonitoringResult"`

	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`
}

// This class does not get 'AdditionalProperties = false' in the schema generation,
// so it can be extended with arbitrary JSON properties to allow adding custom
// data.
type CustomDataType struct {
	// VendorId corresponds to the JSON schema field "vendorId".
	VendorId string `json:"vendorId" yaml:"vendorId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClearMonitoringResultType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["id"]; !ok || v == nil {
		return fmt.Errorf("field id in ClearMonitoringResultType: required")
	}
	if v, ok := raw["status"]; !ok || v == nil {
		return fmt.Errorf("field status in ClearMonitoringResultType: required")
	}
	type Plain ClearMonitoringResultType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ClearMonitoringResultType(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StatusInfoType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["reasonCode"]; !ok || v == nil {
		return fmt.Errorf("field reasonCode in StatusInfoType: required")
	}
	type Plain StatusInfoType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = StatusInfoType(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClearMonitoringStatusEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ClearMonitoringStatusEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ClearMonitoringStatusEnumType, v)
	}
	*j = ClearMonitoringStatusEnumType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClearMonitoringStatusEnumType_1) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ClearMonitoringStatusEnumType_1 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ClearMonitoringStatusEnumType_1, v)
	}
	*j = ClearMonitoringStatusEnumType_1(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomDataType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["vendorId"]; !ok || v == nil {
		return fmt.Errorf("field vendorId in CustomDataType: required")
	}
	type Plain CustomDataType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CustomDataType(plain)
	return nil
}

// Element providing more information about the status.
//
type StatusInfoType struct {
	// Additional text to provide detailed information.
	//
	AdditionalInfo *string `json:"additionalInfo,omitempty" yaml:"additionalInfo,omitempty"`

	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`

	// A predefined code for the reason why the status is returned in this response.
	// The string is case-insensitive.
	//
	ReasonCode string `json:"reasonCode" yaml:"reasonCode"`
}

var enumValues_ClearMonitoringStatusEnumType = []interface{}{
	"Accepted",
	"Rejected",
	"NotFound",
}
var enumValues_ClearMonitoringStatusEnumType_1 = []interface{}{
	"Accepted",
	"Rejected",
	"NotFound",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClearVariableMonitoringResponseJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["clearMonitoringResult"]; !ok || v == nil {
		return fmt.Errorf("field clearMonitoringResult in ClearVariableMonitoringResponseJson: required")
	}
	type Plain ClearVariableMonitoringResponseJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if len(plain.ClearMonitoringResult) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "clearMonitoringResult", 1)
	}
	*j = ClearVariableMonitoringResponseJson(plain)
	return nil
}
