// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package main

import "fmt"
import "encoding/json"
import "reflect"

// UnmarshalJSON implements json.Unmarshaler.
func (j *UploadLogStatusEnumType_1) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_UploadLogStatusEnumType_1 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_UploadLogStatusEnumType_1, v)
	}
	*j = UploadLogStatusEnumType_1(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomDataType) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["vendorId"]; !ok || v == nil {
		return fmt.Errorf("field vendorId in CustomDataType: required")
	}
	type Plain CustomDataType
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CustomDataType(plain)
	return nil
}

type UploadLogStatusEnumType string

type LogStatusNotificationRequestJson struct {
	// CustomData corresponds to the JSON schema field "customData".
	CustomData *CustomDataType `json:"customData,omitempty" yaml:"customData,omitempty"`

	// The request id that was provided in GetLogRequest that started this log upload.
	// This field is mandatory,
	// unless the message was triggered by a TriggerMessageRequest AND there is no log
	// upload ongoing.
	//
	RequestId *int `json:"requestId,omitempty" yaml:"requestId,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status UploadLogStatusEnumType_1 `json:"status" yaml:"status"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UploadLogStatusEnumType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_UploadLogStatusEnumType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_UploadLogStatusEnumType, v)
	}
	*j = UploadLogStatusEnumType(v)
	return nil
}

const UploadLogStatusEnumTypeBadMessage UploadLogStatusEnumType = "BadMessage"
const UploadLogStatusEnumTypeIdle UploadLogStatusEnumType = "Idle"
const UploadLogStatusEnumTypeNotSupportedOperation UploadLogStatusEnumType = "NotSupportedOperation"
const UploadLogStatusEnumTypePermissionDenied UploadLogStatusEnumType = "PermissionDenied"
const UploadLogStatusEnumTypeUploaded UploadLogStatusEnumType = "Uploaded"
const UploadLogStatusEnumTypeUploadFailure UploadLogStatusEnumType = "UploadFailure"
const UploadLogStatusEnumTypeUploading UploadLogStatusEnumType = "Uploading"
const UploadLogStatusEnumTypeAcceptedCanceled UploadLogStatusEnumType = "AcceptedCanceled"

// This class does not get 'AdditionalProperties = false' in the schema generation,
// so it can be extended with arbitrary JSON properties to allow adding custom
// data.
type CustomDataType struct {
	// VendorId corresponds to the JSON schema field "vendorId".
	VendorId string `json:"vendorId" yaml:"vendorId"`
}

type UploadLogStatusEnumType_1 string

const UploadLogStatusEnumType_1_AcceptedCanceled UploadLogStatusEnumType_1 = "AcceptedCanceled"
const UploadLogStatusEnumType_1_BadMessage UploadLogStatusEnumType_1 = "BadMessage"
const UploadLogStatusEnumType_1_Idle UploadLogStatusEnumType_1 = "Idle"
const UploadLogStatusEnumType_1_NotSupportedOperation UploadLogStatusEnumType_1 = "NotSupportedOperation"
const UploadLogStatusEnumType_1_PermissionDenied UploadLogStatusEnumType_1 = "PermissionDenied"
const UploadLogStatusEnumType_1_UploadFailure UploadLogStatusEnumType_1 = "UploadFailure"
const UploadLogStatusEnumType_1_Uploaded UploadLogStatusEnumType_1 = "Uploaded"
const UploadLogStatusEnumType_1_Uploading UploadLogStatusEnumType_1 = "Uploading"

var enumValues_UploadLogStatusEnumType = []interface{}{
	"BadMessage",
	"Idle",
	"NotSupportedOperation",
	"PermissionDenied",
	"Uploaded",
	"UploadFailure",
	"Uploading",
	"AcceptedCanceled",
}
var enumValues_UploadLogStatusEnumType_1 = []interface{}{
	"BadMessage",
	"Idle",
	"NotSupportedOperation",
	"PermissionDenied",
	"Uploaded",
	"UploadFailure",
	"Uploading",
	"AcceptedCanceled",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LogStatusNotificationRequestJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["status"]; !ok || v == nil {
		return fmt.Errorf("field status in LogStatusNotificationRequestJson: required")
	}
	type Plain LogStatusNotificationRequestJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = LogStatusNotificationRequestJson(plain)
	return nil
}
